# Generated by Django 2.1.2 on 2018-11-03 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='classes',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
