# Generated by Django 2.1.2 on 2018-11-29 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='type',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
