# Generated by Django 2.1.2 on 2018-10-05 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('crn', models.IntegerField()),
                ('course_id', models.IntegerField()),
                ('seats', models.IntegerField()),
                ('seats_taken', models.IntegerField()),
                ('instructors', models.CharField(max_length=500)),
                ('periods', models.CharField(max_length=1000)),
            ],
        ),
    ]
