# Generated by Django 2.1.2 on 2018-10-05 21:20
from django.db import migrations
from classes.models import Section
import requests
import json

def get_classes(apps, schema_editor):
    yacs_api_call = "https://yacs.cs.rpi.edu/api/v5/sections.json?show_periods"
    res = requests.get(yacs_api_call)
    sections = res.json()['sections']
    for section in sections:
        name = section['name']
        crn = section['crn']
        seats = section['seats']
        seats_taken = section['seats_taken']
        instructors = section['instructors']
        instructors = json.dumps(instructors)
        periods = section['periods']
        periods = json.dumps(periods)
        s = Section(name=name, crn=crn, seats=seats, seats_taken=seats_taken,
            instructors=instructors, periods=periods)
        s.save()

class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(get_classes)
    ]
