# Generated by Django 2.1.2 on 2018-10-26 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_auto_20181005_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('name', models.CharField(max_length=200)),
                ('course_id', models.CharField(max_length=200)),
                ('sections', models.CharField(max_length=50000)),
            ],
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
