# Generated by Django 2.1.2 on 2018-10-26 19:38

from django.db import migrations
from classes.models import Course
import requests
import json


def get_courses(apps, schema_editor):
    yacs_api_call = """
        https://yacs.cs.rpi.edu/api/v5/courses.json?show_sections&show_periods
    """
    res = requests.get(yacs_api_call)
    courses = res.json()['courses']
    for course in courses:
        name = course['name']
        course_id = course['id']
        # crn = section['crn']
        # seats = section['seats']
        # seats_taken = section['seats_taken']
        # instructors = section['instructors']
        # instructors = json.dumps(instructors)
        # periods = section['periods']
        # section = json.dumps(periods)
        sections = json.dumps(course['sections'])
        c = Course(name=name, course_id=course_id, sections=sections)
        c.save()


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_auto_20181026_1531'),
    ]

    operations = [

    ]
