# Generated by Django 2.1.2 on 2018-11-05 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Studygroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=200)),
                ('course_name', models.CharField(max_length=200)),
                ('time', models.CharField(max_length=200)),
                ('participants', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('rcs', models.CharField(max_length=200)),
                ('token', models.CharField(max_length=200)),
                ('classes', models.CharField(default='', max_length=2000)),
            ],
        ),
    ]
