# Generated by Django 2.1.2 on 2018-11-05 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studygroup',
            name='classes',
        ),
        migrations.RemoveField(
            model_name='studygroup',
            name='password',
        ),
        migrations.RemoveField(
            model_name='studygroup',
            name='rcs',
        ),
        migrations.RemoveField(
            model_name='studygroup',
            name='token',
        ),
        migrations.AddField(
            model_name='studygroup',
            name='day',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
